DROP DATABASE heystk;

CREATE DATABASE heystk;

USE heystk;

CREATE TABLE Agent (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  created DATETIME NOT NULL,
  last_updated DATETIME NOT NULL,
  name VARCHAR(64) NOT NULL,
  authentication VARCHAR(512) NOT NULL UNIQUE
) ENGINE=INNODB;

CREATE TABLE AgentAuthorization (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  expiry DATETIME NOT NULL,
  agent_id INT UNSIGNED NOT NULL
) ENGINE=MEMORY;

ALTER TABLE AgentAuthorization ADD CONSTRAINT AgentAuthorization_Agent_FK FOREIGN KEY (agent_id) REFERENCES Agent (id) ON DELETE CASCADE ON UPDATE CASCADE;